clone:
  clone-nothing:
    image: plugins/git
workspace:
  base: /workdir
  path: code
pipeline:
  build:
    image: gcr.io/time-coin/sbt:latest
    commands:
      - git clone https://github.com/sc-game/test-build.git test-build --depth 1
      - cd /workdir/code/test-build && sbt test

